# Generated by Django 4.2 on 2024-03-18 17:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Заказ')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('required_date', models.DateTimeField(verbose_name='Требуемая дата')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('confirmed', 'Подтверждён'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('payment_method', models.CharField(choices=[('CH', 'Наличные'), ('BC', 'Банковская карта')], max_length=20)),
                ('created_up', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_up', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Козина')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
