# Generated by Django 4.2 on 2024-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_up',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_up',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
