# Generated by Django 4.2 on 2024-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_created_up_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличные'), ('BC', 'Банковская карта')], max_length=20, verbose_name='Метод оплаты'),
        ),
    ]
