# Generated by Django 4.2 on 2024-03-24 14:34

import django.core.validators
from django.db import migrations, models

import candy_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_store', '0002_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=candy_store.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Наличие товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pieces', 'шт'), ('grams', 'гр')], default='pieces', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_stock',
            field=models.PositiveIntegerField(verbose_name='Количество товара на складе'),
        ),
    ]
