# Generated by Django 4.2 on 2024-03-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_up',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated_up',
            new_name='updated_at',
        ),
    ]
